classdef EnableResponse < robotics.ros.Message
    %EnableResponse MATLAB implementation of pr_msgs/EnableResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'pr_msgs/EnableResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4679398f882e7cbdea165980d3ec2888' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Ok
        Reason
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Ok', 'Reason'} % List of non-constant message properties
        ROSPropertyList = {'ok', 'reason'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = EnableResponse(msg)
            %EnableResponse Construct the message object EnableResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function ok = get.Ok(obj)
            %get.Ok Get the value for property Ok
            ok = logical(obj.JavaMessage.getOk);
        end
        
        function set.Ok(obj, ok)
            %set.Ok Set the value for property Ok
            validateattributes(ok, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'EnableResponse', 'Ok');
            
            obj.JavaMessage.setOk(ok);
        end
        
        function reason = get.Reason(obj)
            %get.Reason Get the value for property Reason
            reason = char(obj.JavaMessage.getReason);
        end
        
        function set.Reason(obj, reason)
            %set.Reason Set the value for property Reason
            validateattributes(reason, {'char'}, {}, 'EnableResponse', 'Reason');
            
            obj.JavaMessage.setReason(reason);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Ok = obj.Ok;
            cpObj.Reason = obj.Reason;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Ok = strObj.Ok;
            obj.Reason = strObj.Reason;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Ok = obj.Ok;
            strObj.Reason = obj.Reason;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.pr_msgs.EnableResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.pr_msgs.EnableResponse;
            obj.reload(strObj);
        end
    end
end
