classdef ObjectPoseList < robotics.ros.Message
    %ObjectPoseList MATLAB implementation of pr_msgs/ObjectPoseList
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'pr_msgs/ObjectPoseList' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '8374d419f4435fc3eaa2652d85ff89d7' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        PrMsgsObjectPoseClass = robotics.ros.msg.internal.MessageFactory.getClassForType('pr_msgs/ObjectPose') % Dispatch to MATLAB class for message type pr_msgs/ObjectPose
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
        TimeClass = robotics.ros.msg.internal.MessageFactory.getClassForType('time') % Dispatch to MATLAB class for message type time
    end
    
    properties (Dependent)
        Header
        OriginalTimeStamp
        RequestTimeStamp
        ObjectList
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'ObjectList', [], 'OriginalTimeStamp', [], 'RequestTimeStamp', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'ObjectList', 'OriginalTimeStamp', 'RequestTimeStamp'} % List of non-constant message properties
        ROSPropertyList = {'header', 'object_list', 'originalTimeStamp', 'requestTimeStamp'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ObjectPoseList(msg)
            %ObjectPoseList Construct the message object ObjectPoseList
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ObjectPoseList', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function originaltimestamp = get.OriginalTimeStamp(obj)
            %get.OriginalTimeStamp Get the value for property OriginalTimeStamp
            if isempty(obj.Cache.OriginalTimeStamp)
                obj.Cache.OriginalTimeStamp = feval(obj.TimeClass, obj.JavaMessage.getOriginalTimeStamp);
            end
            originaltimestamp = obj.Cache.OriginalTimeStamp;
        end
        
        function set.OriginalTimeStamp(obj, originaltimestamp)
            %set.OriginalTimeStamp Set the value for property OriginalTimeStamp
            validateattributes(originaltimestamp, {obj.TimeClass}, {'nonempty', 'scalar'}, 'ObjectPoseList', 'OriginalTimeStamp');
            
            obj.JavaMessage.setOriginalTimeStamp(originaltimestamp.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.OriginalTimeStamp)
                obj.Cache.OriginalTimeStamp.setJavaObject(originaltimestamp.getJavaObject);
            end
        end
        
        function requesttimestamp = get.RequestTimeStamp(obj)
            %get.RequestTimeStamp Get the value for property RequestTimeStamp
            if isempty(obj.Cache.RequestTimeStamp)
                obj.Cache.RequestTimeStamp = feval(obj.TimeClass, obj.JavaMessage.getRequestTimeStamp);
            end
            requesttimestamp = obj.Cache.RequestTimeStamp;
        end
        
        function set.RequestTimeStamp(obj, requesttimestamp)
            %set.RequestTimeStamp Set the value for property RequestTimeStamp
            validateattributes(requesttimestamp, {obj.TimeClass}, {'nonempty', 'scalar'}, 'ObjectPoseList', 'RequestTimeStamp');
            
            obj.JavaMessage.setRequestTimeStamp(requesttimestamp.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.RequestTimeStamp)
                obj.Cache.RequestTimeStamp.setJavaObject(requesttimestamp.getJavaObject);
            end
        end
        
        function objectlist = get.ObjectList(obj)
            %get.ObjectList Get the value for property ObjectList
            if isempty(obj.Cache.ObjectList)
                javaArray = obj.JavaMessage.getObjectList;
                array = obj.readJavaArray(javaArray, obj.PrMsgsObjectPoseClass);
                obj.Cache.ObjectList = feval(obj.PrMsgsObjectPoseClass, array);
            end
            objectlist = obj.Cache.ObjectList;
        end
        
        function set.ObjectList(obj, objectlist)
            %set.ObjectList Set the value for property ObjectList
            if ~isvector(objectlist) && isempty(objectlist)
                % Allow empty [] input
                objectlist = feval([obj.PrMsgsObjectPoseClass '.empty'], 0, 1);
            end
            
            validateattributes(objectlist, {obj.PrMsgsObjectPoseClass}, {'vector'}, 'ObjectPoseList', 'ObjectList');
            
            javaArray = obj.JavaMessage.getObjectList;
            array = obj.writeJavaArray(objectlist, javaArray, obj.PrMsgsObjectPoseClass);
            obj.JavaMessage.setObjectList(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.ObjectList)
                obj.Cache.ObjectList = [];
                obj.Cache.ObjectList = obj.ObjectList;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.ObjectList = [];
            obj.Cache.OriginalTimeStamp = [];
            obj.Cache.RequestTimeStamp = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.OriginalTimeStamp = copy(obj.OriginalTimeStamp);
            cpObj.RequestTimeStamp = copy(obj.RequestTimeStamp);
            cpObj.ObjectList = copy(obj.ObjectList);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.OriginalTimeStamp = feval([obj.TimeClass '.loadobj'], strObj.OriginalTimeStamp);
            obj.RequestTimeStamp = feval([obj.TimeClass '.loadobj'], strObj.RequestTimeStamp);
            ObjectListCell = arrayfun(@(x) feval([obj.PrMsgsObjectPoseClass '.loadobj'], x), strObj.ObjectList, 'UniformOutput', false);
            obj.ObjectList = vertcat(ObjectListCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Header = saveobj(obj.Header);
            strObj.OriginalTimeStamp = saveobj(obj.OriginalTimeStamp);
            strObj.RequestTimeStamp = saveobj(obj.RequestTimeStamp);
            strObj.ObjectList = arrayfun(@(x) saveobj(x), obj.ObjectList);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.pr_msgs.ObjectPoseList.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.pr_msgs.ObjectPoseList;
            obj.reload(strObj);
        end
    end
end
