classdef recognitionResponse < robotics.ros.Message
    %recognitionResponse MATLAB implementation of active_vision/recognitionResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'active_vision/recognitionResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '89452d78977e0c6ee0e7a5888de66f5f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        IsNewObject
        ObjectName
        ObjectConfidence
    end
    
    properties (Constant, Hidden)
        PropertyList = {'IsNewObject', 'ObjectConfidence', 'ObjectName'} % List of non-constant message properties
        ROSPropertyList = {'is_new_object', 'object_confidence', 'object_name'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = recognitionResponse(msg)
            %recognitionResponse Construct the message object recognitionResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function isnewobject = get.IsNewObject(obj)
            %get.IsNewObject Get the value for property IsNewObject
            isnewobject = logical(obj.JavaMessage.getIsNewObject);
        end
        
        function set.IsNewObject(obj, isnewobject)
            %set.IsNewObject Set the value for property IsNewObject
            validateattributes(isnewobject, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'recognitionResponse', 'IsNewObject');
            
            obj.JavaMessage.setIsNewObject(isnewobject);
        end
        
        function objectname = get.ObjectName(obj)
            %get.ObjectName Get the value for property ObjectName
            javaArray = obj.JavaMessage.getObjectName;
            array = obj.readJavaArray(javaArray, 'char');
            objectname = arrayfun(@(x) char(x), array, 'UniformOutput', false);
        end
        
        function set.ObjectName(obj, objectname)
            %set.ObjectName Set the value for property ObjectName
            if ~isvector(objectname) && isempty(objectname)
                % Allow empty [] input
                objectname = cell.empty(0,1);
            end
            
            validateattributes(objectname, {'cell'}, {'vector'}, 'recognitionResponse', 'ObjectName');
            if any(cellfun(@(x) ~ischar(x), objectname))
                error(message('robotics:ros:message:CellArrayStringError', ...
                    'objectname'));
            end
            
            javaArray = obj.JavaMessage.getObjectName;
            array = obj.writeJavaArray(objectname, javaArray, 'char');
            obj.JavaMessage.setObjectName(array);
        end
        
        function objectconfidence = get.ObjectConfidence(obj)
            %get.ObjectConfidence Get the value for property ObjectConfidence
            javaArray = obj.JavaMessage.getObjectConfidence;
            array = obj.readJavaArray(javaArray, 'single');
            objectconfidence = single(array);
        end
        
        function set.ObjectConfidence(obj, objectconfidence)
            %set.ObjectConfidence Set the value for property ObjectConfidence
            if ~isvector(objectconfidence) && isempty(objectconfidence)
                % Allow empty [] input
                objectconfidence = single.empty(0,1);
            end
            
            validateattributes(objectconfidence, {'numeric'}, {'vector'}, 'recognitionResponse', 'ObjectConfidence');
            
            javaArray = obj.JavaMessage.getObjectConfidence;
            array = obj.writeJavaArray(objectconfidence, javaArray, 'single');
            obj.JavaMessage.setObjectConfidence(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.IsNewObject = obj.IsNewObject;
            cpObj.ObjectName = obj.ObjectName;
            cpObj.ObjectConfidence = obj.ObjectConfidence;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.IsNewObject = strObj.IsNewObject;
            obj.ObjectName = strObj.ObjectName;
            obj.ObjectConfidence = strObj.ObjectConfidence;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.IsNewObject = obj.IsNewObject;
            strObj.ObjectName = obj.ObjectName;
            strObj.ObjectConfidence = obj.ObjectConfidence;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.active_vision.recognitionResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.active_vision.recognitionResponse;
            obj.reload(strObj);
        end
    end
end
