classdef recognitionRequest < robotics.ros.Message
    %recognitionRequest MATLAB implementation of active_vision/recognitionRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'active_vision/recognitionRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '66069e2f723e28f0e3654ee8e9d20422' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        CameraSerialNumber
    end
    
    properties (Constant, Hidden)
        PropertyList = {'CameraSerialNumber'} % List of non-constant message properties
        ROSPropertyList = {'camera_serial_number'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = recognitionRequest(msg)
            %recognitionRequest Construct the message object recognitionRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function cameraserialnumber = get.CameraSerialNumber(obj)
            %get.CameraSerialNumber Get the value for property CameraSerialNumber
            cameraserialnumber = char(obj.JavaMessage.getCameraSerialNumber);
        end
        
        function set.CameraSerialNumber(obj, cameraserialnumber)
            %set.CameraSerialNumber Set the value for property CameraSerialNumber
            validateattributes(cameraserialnumber, {'char'}, {}, 'recognitionRequest', 'CameraSerialNumber');
            
            obj.JavaMessage.setCameraSerialNumber(cameraserialnumber);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.CameraSerialNumber = obj.CameraSerialNumber;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.CameraSerialNumber = strObj.CameraSerialNumber;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.CameraSerialNumber = obj.CameraSerialNumber;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.active_vision.recognitionRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.active_vision.recognitionRequest;
            obj.reload(strObj);
        end
    end
end
