classdef snapshotResponse < robotics.ros.Message
    %snapshotResponse MATLAB implementation of realsense_camera/snapshotResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'realsense_camera/snapshotResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'b0b40c1ef406c5f500e48880a4dcdfe1' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        PointCloudXyz
        PointCloudRgb
        ColorCameraIntrinsics
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ColorCameraIntrinsics', 'PointCloudRgb', 'PointCloudXyz'} % List of non-constant message properties
        ROSPropertyList = {'color_camera_intrinsics', 'point_cloud_rgb', 'point_cloud_xyz'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = snapshotResponse(msg)
            %snapshotResponse Construct the message object snapshotResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function pointcloudxyz = get.PointCloudXyz(obj)
            %get.PointCloudXyz Get the value for property PointCloudXyz
            javaArray = obj.JavaMessage.getPointCloudXyz;
            array = obj.readJavaArray(javaArray, 'single');
            pointcloudxyz = single(array);
        end
        
        function set.PointCloudXyz(obj, pointcloudxyz)
            %set.PointCloudXyz Set the value for property PointCloudXyz
            if ~isvector(pointcloudxyz) && isempty(pointcloudxyz)
                % Allow empty [] input
                pointcloudxyz = single.empty(0,1);
            end
            
            validateattributes(pointcloudxyz, {'numeric'}, {'vector'}, 'snapshotResponse', 'PointCloudXyz');
            
            javaArray = obj.JavaMessage.getPointCloudXyz;
            array = obj.writeJavaArray(pointcloudxyz, javaArray, 'single');
            obj.JavaMessage.setPointCloudXyz(array);
        end
        
        function pointcloudrgb = get.PointCloudRgb(obj)
            %get.PointCloudRgb Get the value for property PointCloudRgb
            javaArray = obj.JavaMessage.getPointCloudRgb;
            array = obj.readJavaArray(javaArray, 'uint8');
            pointcloudrgb = uint8(array);
        end
        
        function set.PointCloudRgb(obj, pointcloudrgb)
            %set.PointCloudRgb Set the value for property PointCloudRgb
            if ~isvector(pointcloudrgb) && isempty(pointcloudrgb)
                % Allow empty [] input
                pointcloudrgb = uint8.empty(0,1);
            end
            
            validateattributes(pointcloudrgb, {'numeric'}, {'vector'}, 'snapshotResponse', 'PointCloudRgb');
            
            javaArray = obj.JavaMessage.getPointCloudRgb;
            array = obj.writeJavaArray(pointcloudrgb, javaArray, 'uint8');
            obj.JavaMessage.setPointCloudRgb(array);
        end
        
        function colorcameraintrinsics = get.ColorCameraIntrinsics(obj)
            %get.ColorCameraIntrinsics Get the value for property ColorCameraIntrinsics
            javaArray = obj.JavaMessage.getColorCameraIntrinsics;
            array = obj.readJavaArray(javaArray, 'single');
            colorcameraintrinsics = single(array);
        end
        
        function set.ColorCameraIntrinsics(obj, colorcameraintrinsics)
            %set.ColorCameraIntrinsics Set the value for property ColorCameraIntrinsics
            if ~isvector(colorcameraintrinsics) && isempty(colorcameraintrinsics)
                % Allow empty [] input
                colorcameraintrinsics = single.empty(0,1);
            end
            
            validateattributes(colorcameraintrinsics, {'numeric'}, {'vector'}, 'snapshotResponse', 'ColorCameraIntrinsics');
            
            javaArray = obj.JavaMessage.getColorCameraIntrinsics;
            array = obj.writeJavaArray(colorcameraintrinsics, javaArray, 'single');
            obj.JavaMessage.setColorCameraIntrinsics(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.PointCloudXyz = obj.PointCloudXyz;
            cpObj.PointCloudRgb = obj.PointCloudRgb;
            cpObj.ColorCameraIntrinsics = obj.ColorCameraIntrinsics;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.PointCloudXyz = strObj.PointCloudXyz;
            obj.PointCloudRgb = strObj.PointCloudRgb;
            obj.ColorCameraIntrinsics = strObj.ColorCameraIntrinsics;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.PointCloudXyz = obj.PointCloudXyz;
            strObj.PointCloudRgb = obj.PointCloudRgb;
            strObj.ColorCameraIntrinsics = obj.ColorCameraIntrinsics;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.realsense_camera.snapshotResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.realsense_camera.snapshotResponse;
            obj.reload(strObj);
        end
    end
end
