function outOfUintIdx = checkOutUinit(ARCUnit, points3dwrd)
outOfUintIdx = points3dwrd(1,:)<ARCUnit.Tote.Range(1)|points3dwrd(1,:)>ARCUnit.Tote.Range(4)...
               |points3dwrd(2,:)<ARCUnit.Tote.Range(2)|points3dwrd(2,:)>ARCUnit.Tote.Range(5)...
               |points3dwrd(3,:)<ARCUnit.Tote.Range(3)-0.05|points3dwrd(3,:)>ARCUnit.Tote.Range(6);
end