classdef GetPoseResponse < robotics.ros.Message
    %GetPoseResponse MATLAB implementation of manual_fit/GetPoseResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'manual_fit/GetPoseResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '103b82904e3f4e9b1280818fa74ca44b' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        PrMsgsObjectPoseListClass = robotics.ros.msg.internal.MessageFactory.getClassForType('pr_msgs/ObjectPoseList') % Dispatch to MATLAB class for message type pr_msgs/ObjectPoseList
    end
    
    properties (Dependent)
        Pa
    end
    
    properties (Access = protected)
        Cache = struct('Pa', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Pa'} % List of non-constant message properties
        ROSPropertyList = {'pa'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = GetPoseResponse(msg)
            %GetPoseResponse Construct the message object GetPoseResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function pa = get.Pa(obj)
            %get.Pa Get the value for property Pa
            if isempty(obj.Cache.Pa)
                obj.Cache.Pa = feval(obj.PrMsgsObjectPoseListClass, obj.JavaMessage.getPa);
            end
            pa = obj.Cache.Pa;
        end
        
        function set.Pa(obj, pa)
            %set.Pa Set the value for property Pa
            validateattributes(pa, {obj.PrMsgsObjectPoseListClass}, {'nonempty', 'scalar'}, 'GetPoseResponse', 'Pa');
            
            obj.JavaMessage.setPa(pa.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Pa)
                obj.Cache.Pa.setJavaObject(pa.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Pa = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Pa = copy(obj.Pa);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Pa = feval([obj.PrMsgsObjectPoseListClass '.loadobj'], strObj.Pa);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Pa = saveobj(obj.Pa);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.manual_fit.GetPoseResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.manual_fit.GetPoseResponse;
            obj.reload(strObj);
        end
    end
end
