classdef HallEffectData < robotics.ros.Message
    %HallEffectData MATLAB implementation of apc_arduino/HallEffectData
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'apc_arduino/HallEffectData' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '45bf37d1a93e6cd163dd5d8f03134e83' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        HE0
        HE1
        HE2
        HE3
    end
    
    properties (Constant, Hidden)
        PropertyList = {'HE0', 'HE1', 'HE2', 'HE3'} % List of non-constant message properties
        ROSPropertyList = {'HE0', 'HE1', 'HE2', 'HE3'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = HallEffectData(msg)
            %HallEffectData Construct the message object HallEffectData
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function he0 = get.HE0(obj)
            %get.HE0 Get the value for property HE0
            he0 = typecast(int16(obj.JavaMessage.getHE0), 'uint16');
        end
        
        function set.HE0(obj, he0)
            %set.HE0 Set the value for property HE0
            validateattributes(he0, {'numeric'}, {'nonempty', 'scalar'}, 'HallEffectData', 'HE0');
            
            obj.JavaMessage.setHE0(he0);
        end
        
        function he1 = get.HE1(obj)
            %get.HE1 Get the value for property HE1
            he1 = typecast(int16(obj.JavaMessage.getHE1), 'uint16');
        end
        
        function set.HE1(obj, he1)
            %set.HE1 Set the value for property HE1
            validateattributes(he1, {'numeric'}, {'nonempty', 'scalar'}, 'HallEffectData', 'HE1');
            
            obj.JavaMessage.setHE1(he1);
        end
        
        function he2 = get.HE2(obj)
            %get.HE2 Get the value for property HE2
            he2 = typecast(int16(obj.JavaMessage.getHE2), 'uint16');
        end
        
        function set.HE2(obj, he2)
            %set.HE2 Set the value for property HE2
            validateattributes(he2, {'numeric'}, {'nonempty', 'scalar'}, 'HallEffectData', 'HE2');
            
            obj.JavaMessage.setHE2(he2);
        end
        
        function he3 = get.HE3(obj)
            %get.HE3 Get the value for property HE3
            he3 = typecast(int16(obj.JavaMessage.getHE3), 'uint16');
        end
        
        function set.HE3(obj, he3)
            %set.HE3 Set the value for property HE3
            validateattributes(he3, {'numeric'}, {'nonempty', 'scalar'}, 'HallEffectData', 'HE3');
            
            obj.JavaMessage.setHE3(he3);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.HE0 = obj.HE0;
            cpObj.HE1 = obj.HE1;
            cpObj.HE2 = obj.HE2;
            cpObj.HE3 = obj.HE3;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.HE0 = strObj.HE0;
            obj.HE1 = strObj.HE1;
            obj.HE2 = strObj.HE2;
            obj.HE3 = strObj.HE3;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.HE0 = obj.HE0;
            strObj.HE1 = obj.HE1;
            strObj.HE2 = obj.HE2;
            strObj.HE3 = obj.HE3;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.apc_arduino.HallEffectData.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.apc_arduino.HallEffectData;
            obj.reload(strObj);
        end
    end
end
