classdef MoveToPosRequest < robotics.ros.Message
    %MoveToPosRequest MATLAB implementation of apc_arduino/MoveToPosRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'apc_arduino/MoveToPosRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '80bf00435ef02088350aec13d2fc15aa' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        SpNo
        Pos
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Pos', 'SpNo'} % List of non-constant message properties
        ROSPropertyList = {'pos', 'sp_no'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MoveToPosRequest(msg)
            %MoveToPosRequest Construct the message object MoveToPosRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function spno = get.SpNo(obj)
            %get.SpNo Get the value for property SpNo
            spno = typecast(int8(obj.JavaMessage.getSpNo), 'uint8');
        end
        
        function set.SpNo(obj, spno)
            %set.SpNo Set the value for property SpNo
            validateattributes(spno, {'numeric'}, {'nonempty', 'scalar'}, 'MoveToPosRequest', 'SpNo');
            
            obj.JavaMessage.setSpNo(spno);
        end
        
        function pos = get.Pos(obj)
            %get.Pos Get the value for property Pos
            pos = int16(obj.JavaMessage.getPos);
        end
        
        function set.Pos(obj, pos)
            %set.Pos Set the value for property Pos
            validateattributes(pos, {'numeric'}, {'nonempty', 'scalar'}, 'MoveToPosRequest', 'Pos');
            
            obj.JavaMessage.setPos(pos);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.SpNo = obj.SpNo;
            cpObj.Pos = obj.Pos;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.SpNo = strObj.SpNo;
            obj.Pos = strObj.Pos;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.SpNo = obj.SpNo;
            strObj.Pos = obj.Pos;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.apc_arduino.MoveToPosRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.apc_arduino.MoveToPosRequest;
            obj.reload(strObj);
        end
    end
end
