classdef ServiceBridgeRequest < robotics.ros.Message
    %ServiceBridgeRequest MATLAB implementation of apc_arduino/ServiceBridgeRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'apc_arduino/ServiceBridgeRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'b74f88db399aa5b0116a9e4b49d12af0' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Service
        Channel
        Value
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Channel', 'Service', 'Value'} % List of non-constant message properties
        ROSPropertyList = {'channel', 'service', 'value'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ServiceBridgeRequest(msg)
            %ServiceBridgeRequest Construct the message object ServiceBridgeRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function service = get.Service(obj)
            %get.Service Get the value for property Service
            service = typecast(int8(obj.JavaMessage.getService), 'uint8');
        end
        
        function set.Service(obj, service)
            %set.Service Set the value for property Service
            validateattributes(service, {'numeric'}, {'nonempty', 'scalar'}, 'ServiceBridgeRequest', 'Service');
            
            obj.JavaMessage.setService(service);
        end
        
        function channel = get.Channel(obj)
            %get.Channel Get the value for property Channel
            channel = typecast(int8(obj.JavaMessage.getChannel), 'uint8');
        end
        
        function set.Channel(obj, channel)
            %set.Channel Set the value for property Channel
            validateattributes(channel, {'numeric'}, {'nonempty', 'scalar'}, 'ServiceBridgeRequest', 'Channel');
            
            obj.JavaMessage.setChannel(channel);
        end
        
        function value = get.Value(obj)
            %get.Value Get the value for property Value
            value = int16(obj.JavaMessage.getValue);
        end
        
        function set.Value(obj, value)
            %set.Value Set the value for property Value
            validateattributes(value, {'numeric'}, {'nonempty', 'scalar'}, 'ServiceBridgeRequest', 'Value');
            
            obj.JavaMessage.setValue(value);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Service = obj.Service;
            cpObj.Channel = obj.Channel;
            cpObj.Value = obj.Value;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Service = strObj.Service;
            obj.Channel = strObj.Channel;
            obj.Value = strObj.Value;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Service = obj.Service;
            strObj.Channel = obj.Channel;
            strObj.Value = obj.Value;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.apc_arduino.ServiceBridgeRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.apc_arduino.ServiceBridgeRequest;
            obj.reload(strObj);
        end
    end
end
