classdef SuctionSensData < robotics.ros.Message
    %SuctionSensData MATLAB implementation of apc_arduino/SuctionSensData
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'apc_arduino/SuctionSensData' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'ce09ba216647886aa9349ce4bcd73439' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        SucSen0
        SucSen1
    end
    
    properties (Constant, Hidden)
        PropertyList = {'SucSen0', 'SucSen1'} % List of non-constant message properties
        ROSPropertyList = {'SucSen0', 'SucSen1'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SuctionSensData(msg)
            %SuctionSensData Construct the message object SuctionSensData
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function sucsen0 = get.SucSen0(obj)
            %get.SucSen0 Get the value for property SucSen0
            sucsen0 = typecast(int16(obj.JavaMessage.getSucSen0), 'uint16');
        end
        
        function set.SucSen0(obj, sucsen0)
            %set.SucSen0 Set the value for property SucSen0
            validateattributes(sucsen0, {'numeric'}, {'nonempty', 'scalar'}, 'SuctionSensData', 'SucSen0');
            
            obj.JavaMessage.setSucSen0(sucsen0);
        end
        
        function sucsen1 = get.SucSen1(obj)
            %get.SucSen1 Get the value for property SucSen1
            sucsen1 = typecast(int16(obj.JavaMessage.getSucSen1), 'uint16');
        end
        
        function set.SucSen1(obj, sucsen1)
            %set.SucSen1 Set the value for property SucSen1
            validateattributes(sucsen1, {'numeric'}, {'nonempty', 'scalar'}, 'SuctionSensData', 'SucSen1');
            
            obj.JavaMessage.setSucSen1(sucsen1);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.SucSen0 = obj.SucSen0;
            cpObj.SucSen1 = obj.SucSen1;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.SucSen0 = strObj.SucSen0;
            obj.SucSen1 = strObj.SucSen1;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.SucSen0 = obj.SucSen0;
            strObj.SucSen1 = obj.SucSen1;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.apc_arduino.SuctionSensData.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.apc_arduino.SuctionSensData;
            obj.reload(strObj);
        end
    end
end
